### ISSUE TITLE
Eclipse css import url leads to the incorrect page.

### ISSUE THREAD

**Issue by Variapolis** [nextr0ll/nextr0ll.github.io#1]
Eclipse doesn't work due to the url being missing.

**Comment by Variapolis** [comment]
Currently fixed my copy by copying css into the file itself.

**Comment by Curtis-D** [comment]
That's an issue with the website which has been fixed now. Feel free to close @nextr0ll

**Comment by Variapolis** [comment]
Fixed. Thank you.
